### ISSUE TITLE
[QUESTION] I don't understand how to run this module

### ISSUE THREAD

**Issue by teekamsuthar** [Badisi/samsung-tv-remote#10]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Library version

18

### Description

Could you please help me? :)

### Environment

- **OS Name**:
- **System Model Name**:
- **npm**:
- **Node.js**:

**Comment by Badisi** [comment]
This is a NodeJS module.

1) Make sure you have [NodeJS](https://nodejs.org/en) installed on your machine (it will come with `npm` which is the package manager for node)
2) Create a folder `my-project`
3) Go inside the folder `cd my-project`
4) Initialize a new node project `npm init`
5) Install the package `npm install samsung-tv-remote --save`
6) Create a file `test.js`
7) Copy / paste this example in `test.js` :
```ts
const { SamsungTvRemote, Keys } = require('samsung-tv-remote');

const main = async () => {
    const remote = new SamsungTvRemote({
        ip: '192.168.1.111',
        mac: 'fc:03:9f:0d:72:37'
    });
    await remote.wakeTV();
    await remote.sendKey(Keys.KEY_DOWN);
    await remote.sendKeys([Keys.KEY_POWER]);
};
main().catch(console.error);
```
8) Replace `ip` and `mac` with your own TV info (search on google how to find them)
9) Run the program `node test.js`
10) Enjoy ;-)
