### ISSUE TITLE
[FEAT] Two TVs on same network, one token

### ISSUE THREAD

**Issue by arjan-io** [Badisi/samsung-tv-remote#11]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Library version

latest

### Description

I am in the need of controlling two TVs on the same network. For simplicity, call them TV1 and TV2. The WoL function works fine for both, however any subsequent command make use of the Token. TV1 supplied the token first and thus works without any problems. TV2 however, keeps asking if I want to grant access from _samsung-tv-remote_ and in the debug log, shows the token of TV1.

Running a RPI4, I tried installing this repo in separate folders without using sudo as to not install this globally on the system. Still, I get the same token replied in debug-mode and TV2 keeps asking for permission.

How can I fix this?

### Environment

- **Raspian Bullseye**:
- **RPI4 1GB**:
- **npm 10.9.0**:
- **Node.js 18.17.1**:

**Comment by Badisi** [comment]
This library acts as an app to your tv.
The name you give to this app, will be linked to a single token given by the tv.
So if you are using the same app on multiple tvs, then each token will override the previous one.
Same if you use multiple instances of the same app but keep the same app name.

As an improvement, I've made a little patch to the way the tokens are saved so that one app could have multiple tv (=ip+port) registered.

**Comment by Badisi** [comment]
:rocket: Released in [samsung-tv-remote@2.2.0](https://github.com/Badisi/samsung-tv-remote/releases/tag/2.2.0)

**Comment by arjan-io** [comment]
Thank you for the quick fix!

`The name you give to this app, will be linked to a single token given by the tv.`
Just for my reference, how would I change the name of the app?

Thank you.

**Comment by Badisi** [comment]
Have a look at the [Usage#options](https://github.com/Badisi/samsung-tv-remote?tab=readme-ov-file#usage) section, there is a **name** property:

```ts
const remote = new SamsungTvRemote({
  name: 'My app' // defaults to 'SamsungTvRemote'
});
```

**Comment by arjan-io** [comment]
Could you please tell me where I can delete my token? The old one seems to persist somewhere. Thx

**Comment by Badisi** [comment]
Cache is saved here:
https://github.com/Badisi/samsung-tv-remote/blob/8fd455643f6ab44eeb45d4abf01ae9c6441ca2b9/src/remote.ts#L127-L137

**Comment by arjan-io** [comment]
Thank. Now I cleared it, it works perfect. Thanks for this package!
