### ISSUE TITLE
Hello I tried to use this package to connect samsung smart tv

### ISSUE THREAD

**Issue by parthagraz** [Badisi/samsung-tv-remote#2]
I added some console and they returned true for isAlive funciton. 
but getting 
{ Error: connect ECONNREFUSED 192.168.2.89:8001
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1107:14)
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '192.168.2.89',
  port: 8001 } 'This is the error'

for ws connection.

**Comment by Badisi** [comment]
Sorry for the late reply.
To me it sounds like there is something wrong with the port.
Try checking if port 8001 is not already in use.
