### ISSUE TITLE
[FEATURE] bufferUtil.mask is not a function

### ISSUE THREAD

**Issue by patuwwy** [Badisi/samsung-tv-remote#9]
### Documentation can be submitted with pull requests

- [X] I know that I can edit the docs myself but prefer to file this issue instead

### Description

[SamsungTvRemote]: Token found: XXXXXXXX
[SamsungTvRemote]: Connecting to TV: wss://192.168.1.17:8002/api/v2/channels/samsung.remote.control?name=YYYYYYYYYYY&token=XXXXXXXX
[SamsungTvRemote]: Sending key: KEY_POWER
 ⨯ TypeError: bufferUtil.mask is not a function
    at module.exports.mask (webpack-internal:///(rsc)/./node_modules/ws/lib/buffer-util.js:121:23)
    at Sender.frame (webpack-internal:///(rsc)/./node_modules/ws/lib/sender.js:139:9)
    at Sender.dispatch (webpack-internal:///(rsc)/./node_modules/ws/lib/sender.js:467:35)
    at Sender.send (webpack-internal:///(rsc)/./node_modules/ws/lib/sender.js:387:18)
    at WebSocket.send (webpack-internal:///(rsc)/./node_modules/ws/lib/websocket.js:477:18)
      at SamsungTvRemote.sendKey(webpack - internal:///(rsc)/./app/utils/samsung-tv-remote/src/remote.ts:75:24)

I have to set ENV `WS_NO_BUFFER_UTIL=1` to get it working

**Comment by Badisi** [comment]
This library is using the `ws` package and as stated in their [documentation](https://github.com/websockets/ws/tree/master?tab=readme-ov-file#opt-in-for-performance):
> [bufferutil](https://github.com/websockets/bufferutil) is an optional module that can be installed alongside the ws module

So users can choose to install `bufferutil` or use the [WS_NO_BUFFER_UTIL](https://github.com/websockets/ws/blob/master/doc/ws.md#ws_no_buffer_util) environment variable to opt-out.

----

As this is something that improves the performance, I have decided to include `bufferutil` by default as **optionalDependencies**. As a result `bufferutil` should now be installed automatically during install, which should fix the problem.

But this is a binary addon, so it may not install in certain cases, such as incompatibilities with your current platform. So in such cases, using `WS_NO_BUFFER_UTIL=1` will be ncessary (N.B. it is now documented in the [FAQ](https://github.com/Badisi/samsung-tv-remote/edit/main/README.md#im-getting-a-typeerror-bufferutilmask-is-not-a-function)).

----

Thanks for the report 👍

**Comment by Badisi** [comment]
:rocket: Released in [samsung-tv-remote@2.1.0](https://github.com/Badisi/samsung-tv-remote/releases/tag/2.1.0)

**Comment by patuwwy** [comment]
thx!
